### PR TITLE
feat: rule and script bed_to_bedpe

### PR DESCRIPTION
**Pull request by AKBrueggemann**
# Description

 A rule and a script for converting a .bed file containing information about the primer into a .bedpe file. The .bedpe file format is used in the workflow.

## Related Issue

 #381

## Checklist

- [x] I've formatted the PR title in accordance with the [structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I've updated the code style using [`pre-commit`](https://ikim-essen.github.io/uncovar/dev-guide/contributing/#pre-commit) if needed.
- [ ] I've updated or supplemented the documentation as needed.
- [x] I've read the [`CODE_OF_CONDUCT.md`] document.
- [x] I've read the [`CONTRIBUTING.md`] guide.

[`CODE_OF_CONDUCT.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CODE_OF_CONDUCT.md
[`CONTRIBUTING.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by thomasbtf** [comment]
Nice work 👍 I think we should place the ARTIC V3 default prime bed file in the resources and make it adjustable via the config. So anybody can adjust the primer scheme given to the workflow. What do you think?

**Comment by AKBrueggemann** [comment]
So you mean that in the config there should be the path to the bed file? And should the path to the bedpe file stay in the config?

**Comment by thomasbtf** [comment]
The path to the `.bed` file in the config is probably enough because the workflow will generate the `.bedpe`.

**Comment by thomasbtf** [comment]
Looks good to me. @alethomas, what do you think about this? Folker wants us to look more closely at the PR and changes to the code.

**Comment by thomasbtf** [comment]
Maybe the docs should be updated and explain how to use a custom primer file. Best placement would be probably [here](https://ikim-essen.github.io/uncovar/user-guide/configuration/).

**Review by alethomas — COMMENTED** [review]
Are you sure you want to include the bed file in our repo and not making the workflow downloading it? As it's not our primer set I'd prefer that

**Comment by thomasbtf** [comment]
That is actually a good idea. However, then we have to think about handling "local" primer files via then config. It could be the case, that doesn't want to use the ARTIC primers or primer files, that are only downloadable via a URL.

Maybe add a function that checks if the entry in the config is a URL or a path. Upon this check, the file is either downloaded or locally found.

What do you think?

**Comment by thomasbtf** [comment]
@alethomas, @AKBrueggemann: What do you think?

**Comment by alethomas** [comment]
> 

I really like this idea, @AKBrueggemann ?

**Comment by AKBrueggemann** [comment]
Alright, I'll change it, it is a good idea :)

**Comment by thomasbtf** [comment]
@alethomas Could you please also review? :)

**Review by thomasbtf — APPROVED** [review]

**Pull request merged**
