### PR TITLE
chore: checkout full history for formatting

### PR DESCRIPTION
**Pull request by johanneskoester**
# Description

## Checklist

- [x] I've formatted the PR title in accordance with the [structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I've updated the code style using [`pre-commit`](https://ikim-essen.github.io/uncovar/dev-guide/contributing/#pre-commit) if needed.
- [x] I've updated or supplemented the documentation as needed.
- [x] I've read the [`CODE_OF_CONDUCT.md`] document.
- [x] I've read the [`CONTRIBUTING.md`] guide.

[`CODE_OF_CONDUCT.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CODE_OF_CONDUCT.md
[`CONTRIBUTING.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by huzuner** [comment]
Conda command is not being found in some technology tests and in one benchmark test? Could this also be about the recent conda changes on snakemake?

**Comment by johanneskoester** [comment]
@alethomas unexpected failures here. Seems like a bug in pangolin's internal usage of the snakemake api.

**Comment by johanneskoester** [comment]
Ok, I think I found the problem. Seems to be fixed in the latest pangolin release.

**Comment by johanneskoester** [comment]
However, this is not yet merged: https://github.com/bioconda/bioconda-recipes/pull/42192

**Comment by huzuner** [comment]
`curl: (28) Failed to connect to eutils.ncbi.nlm.nih.gov port 443 after 20000 ms: Timeout was reached` I guess there were some connections issues there. Could you perhaps rerun the tests?

**Comment by alethomas** [comment]
I already made a PR for the spades update but I guess in order to get this one working I need to merge it

**Comment by huzuner** [comment]
One of the technology tests is failing with: 
```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
This also seems to be present in the master branch.
Could that be because of using the same path in `Upload logs` for both benchmark and technology tests:
https://github.com/IKIM-Essen/uncovar/blob/75bd2e7f1cc803f31e8bc36066ab813ee5dd5fb2/.github/workflows/main.yml#L185 and https://github.com/IKIM-Essen/uncovar/blob/75bd2e7f1cc803f31e8bc36066ab813ee5dd5fb2/.github/workflows/main.yml#L377

**Review by alethomas — APPROVED** [review]

**Pull request merged**
